### ISSUE TITLE
model  猫咪模型

### ISSUE THREAD

**Issue by wuyongyu** [zcxiaobao/vscode-cats#3]
<html>
<body>

vscode-cats.model | 选择喵咪模型
-- | --

</body>
</html>

请问这个 `model` 里面有哪些模型？
目前看到是传字符串类型，不清楚要传什么值

**Comment by wuyongyu** [comment]
哦哦 查到了
- 白猫：`tororo` 和 黑猫： `hijiki`

**Comment by zcxiaobao** [comment]
在github搜索 live2d，还可以搜索到很多人物模型，模型会有名字。找到模型名字后，直接替换【***】部分即可: https://unpkg.com/【live2d-widget-model-hijiki】/assets/hijiki.model.json

当时因为是参加活动，我只提供了喵咪模型。
